# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-15 11:30
from __future__ import unicode_literals

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to=App.models.path_upload_rule)),
            ],
        ),
    ]
